spring:
  application:
    name: web-recommend
  #数据库的连接信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3307/web
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:  root
    password:  123456

#mybatis的相关配置
mybatis:
  configuration:
    #打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true
